import Head from 'next/head'
import Footer from '../components/footer/footer';
import ResponsiveAppBar from "../components/navbar/navbar";
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ResponsiveAppBar/>

      <main>
        <h1 >
        Aca van a ver Cards
        </h1>

      </main>

      <Footer />

    </div>
  )
}
