import Head from 'next/head'
import Footer from '../components/Footer/footer';
import Main from '../components/Main/main';
import ResponsiveAppBar from "../components/Navbar/navbar";
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ResponsiveAppBar/>

      
        <Main/>
      

      <Footer />

    </div>
  )
}
